import Head from "next/head";

import {
  getCategory,
  getAttributeLimitedProducts,
} from "../supabaseApi/getProductHandler";

// Components
import CategoryList from "../components/home/categoryList";
import FilterProductsList from "../components/home/filterProductsList";

export default function Home({
  categories,
  newProducts,
  bestSellerProducts,
  ourPickProducts,
}) {
  return (
    <div>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CategoryList category={categories} />
      <FilterProductsList
        newProducts={newProducts}
        bestSellerProducts={bestSellerProducts}
        ourPickProducts={ourPickProducts}
      />
    </div>
  );
}

export async function getServerSideProps() {
  const categories = await getCategory();
  const newProducts = await getAttributeLimitedProducts("New");
  const bestSellerProducts = await getAttributeLimitedProducts("Best Seller");
  const ourPickProducts = await getAttributeLimitedProducts("Our Pick");

  return {
    props: { categories, newProducts, bestSellerProducts, ourPickProducts },
  };
}
